force-app/main/default/objects/Playlist_Song__c/Playlist_Song__c.object-meta.xml
<CustomObject>
    <label>Playlist Song</label>
    <nameField>
        <label>Playlist Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlist Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist_Song__c/fields/PlaylistId__c.field-meta.xml
<CustomField>
    <fullName>PlaylistId__c</fullName>
    <label>PlaylistId</label>
    <referenceTo>User_Playlist__c</referenceTo>
    <relationshipName>playlist_songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/PlaylistSongSelector.cls
/**
 * @description       : 
 * @author            : Eduardo Mendez Miranda
 * @group             : 
 * @last modified on  : 09-08-2025
 * @last modified by  : Eduardo Mendez Miranda
**/
public with sharing class PlaylistSongSelector {
    
    
    public static List<Playlist_Song__c> getByPlaylist(Id playlistId) {
        return [
            SELECT Id
            FROM Playlist_Song__c
            WHERE PlaylistId__c = :playlistId
        ];
    }
}