force-app/main/default/objects/Playlist_Song__c/Playlist_Song__c.object-meta.xml
<CustomObject>
    <label>Playlist Song</label>
    <nameField>
        <label>Playlist Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Playlist Songs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Playlist_Song__c/fields/PlaylistId__c.field-meta.xml
<CustomField>
    <fullName>PlaylistId__c</fullName>
    <label>PlaylistId</label>
    <referenceTo>User_Playlist__c</referenceTo>
    <relationshipName>playlist_songs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Playlist_Song__c/fields/SongId__c.field-meta.xml
<CustomField>
    <fullName>SongId__c</fullName>
    <label>SongId</label>
    <referenceTo>Song__c</referenceTo>
    <relationshipName>playlist_songs</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/Genre__c.field-meta.xml
<CustomField>
    <fullName>Genre__c</fullName>
    <label>Genre</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Song__c/fields/IsPublic__c.field-meta.xml
<CustomField>
    <fullName>IsPublic__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsPublic</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/User_Playlist__c/User_Playlist__c.object-meta.xml
<CustomObject>
    <label>User Playlist</label>
    <nameField>
        <label>User Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Playlists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/TodayPlaylistScheduleJob.cls
/**
 * @description       : 
 * @author            : Eduardo Mendez Miranda
 * @group             : 
 * @last modified on  : 09-08-2025
 * @last modified by  : Eduardo Mendez Miranda
**/
public with sharing class TodayPlaylistScheduleJob implements Schedulable{
    public void execute(SchedulableContext sc) {
        
        try {
            updateReleasedTodayPlaylist();    
        } catch (Exception e ) {
             System.debug('Error in Scheduled Job updateReleasedTodayPlaylist: ' + e.getMessage());
            System.debug('Stack Trace: ' + e.getStackTraceString());
        }
    }

    private void updateReleasedTodayPlaylist() {

        //get today songs
         Map<Id, Song__c> todaysSongsMap = SongsSelector.getTodaysPublicSongsMap();

        //check if the playlist released today exist
        List<User_Playlist__c> releasedTodayPlaylist = UserPlaylistSelector.getPlaylistByName('Released Today');

        if (releasedTodayPlaylist == null) {
                releasedTodayPlaylist.add(new User_Playlist__c(
                    Name = 'Released Today',
                    IsPublic__c = TRUE
                ));
                insert releasedTodayPlaylist;
            }

        // get old links and delete them
        List<Playlist_Song__c> oldLinks = PlaylistSongSelector.getByPlaylist(releasedTodayPlaylist[0].Id);
        
        if (!oldLinks.isEmpty()) {
            delete oldLinks;
        }

        //reading and insert the songs on the Playlist Released Today
        if (!todaysSongsMap.isEmpty()) {
            List<Playlist_Song__c> songsToInsert = new List<Playlist_Song__c>();

               for (Song__c song : todaysSongsMap.values()) {
                songsToInsert.add(new Playlist_Song__c(
                    PlaylistId__c = releasedTodayPlaylist[0].Id,
                    SongId__c = song.Id,
                    Duration__c = song.Duration__c,
                    Genre__c = song.Genre__c,
                    Name = song.Name
                ));
            }
            
            
                insert songsToInsert; 
            
        }
    }
}