force-app/main/default/objects/Song__c/Song__c.object-meta.xml
<CustomObject>
    <label>Song</label>
    <nameField>
        <label>Song Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Songs</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Song__c/fields/ArtistId__c.field-meta.xml
<CustomField>
    <fullName>ArtistId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>ArtistId</label>
    <referenceTo>Artist__c</referenceTo>
    <relationshipLabel>Songs</relationshipLabel>
    <relationshipName>songs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/SongsSelector.cls
/**
 * @description       : 
 * @author            : Eduardo Mendez Miranda
 * @group             : 
 * @last modified on  : 08-24-2025
 * @last modified by  : Eduardo Mendez Miranda
**/
public with sharing class SongsSelector {


    @AuraEnabled
    public static List<Song__c> getUpcommingSongs() {
        List<Song__c> allSongs = [
                SELECT Id, Name, Duration__c, release_date__c, artistId__c
                FROM Song__c
                WHERE release_date__c = LAST_N_DAYS:15
                ORDER BY Name ASC
        ];
    }
}