force-app/main/default/objects/User__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <displayFormat>{0}</displayFormat>
    <label>UserId</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/User_Playlist__c/User_Playlist__c.object-meta.xml
<CustomObject>
    <label>User Playlist</label>
    <nameField>
        <label>User Playlist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>User Playlists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/User_Playlist__c/fields/Cant_Songs__c.field-meta.xml
<CustomField>
    <fullName>Cant_Songs__c</fullName>
    <label>Cant_Songs</label>
    <summaryForeignKey>Playlist_Song__c.PlaylistId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Playlist__c/fields/Playtime__c.field-meta.xml
<CustomField>
    <fullName>Playtime__c</fullName>
    <label>Playtime</label>
    <summarizedField>Playlist_Song__c.Duration_Song__c</summarizedField>
    <summaryForeignKey>Playlist_Song__c.PlaylistId__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/objects/User_Playlist__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User__c</referenceTo>
    <relationshipName>user_playlists</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/PlaylistSelector.cls
/**
 * @description       : 
 * @author            : Eduardo Mendez Miranda
 * @group             : 
 * @last modified on  : 08-24-2025
 * @last modified by  : Eduardo Mendez Miranda
**/
public with sharing class PlaylistSelector {
    
    /**
     * @description Retrieves the five most recently modified playlists for the specified user.
     * @param userId The Id of the User__c record whose playlists should be retrieved.
     * @return A list of up to 5 User_Playlist__c records, ordered by LastModifiedDate (descending).
     * @example List<User_Playlist__c> playlists = PlaylistSelector.getLastModifiedPlaylist(UserInfo.getUserId());
     */
    public static List<User_Playlist__c> getLastModifiedPlaylist(Id userId){
        return[
            SELECT 
            Id,
            Name,
            Cant_Songs__c,
            Playtime__c, 
            LastModifiedDate  
            FROM User_Playlist__c 
            WHERE UserId__c = :userId
            ORDER BY LastModifiedDate 
            DESC LIMIT 5
        ];
    }
}